name: Deploy GCP ETL
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pulumi/actions@v6
      working-directory: .
      with:
        command: preview
        stack-name: sarigela67/gcp-etl/dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  deploy:
    needs: preview
    runs-on: ubuntu-latest
    if: github.ref

